language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - ruby-head
  - rbx-3
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx-3
gemfile: .travis.gemfile
script: bundle exec rake spec_travis
before_script:
  - psql -c 'create database rodauth_test;' -U postgres
addons:
  postgresql: "9.4"
services:
  - postgresql
